import os
import json
import glob

# Path relative to scripts/JEE/ location
# Points to: ../../ROOT/JEE/OUTPUT
ROOT_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "ROOT", "JEE", "OUTPUT")

def generate_html_report(outer_set_name, all_questions, output_path):
    """Generates a visual HTML report for the Combined JEE Set."""
    
    # Sort by question number only
    all_questions.sort(key=lambda q: int(q.get("question_no", 0)))
    
    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>Verification: {outer_set_name}</title>
        <style>
            body {{ font-family: 'Segoe UI', sans-serif; padding: 20px; background: #f4f6f9; }}
            .container {{ max-width: 1000px; margin: 0 auto; }}
            .card {{ background: white; padding: 20px; margin-bottom: 20px; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.08); border-left: 5px solid #ccc; }}
            .card.math {{ border-left-color: #3498db; }}
            .card.phy {{ border-left-color: #e74c3c; }}
            .card.chem {{ border-left-color: #f1c40f; }}
            .header {{ display: flex; justify-content: space-between; font-weight: 600; border-bottom: 1px solid #eee; padding-bottom: 10px; margin-bottom: 15px; }}
            .badge {{ padding: 4px 10px; border-radius: 12px; color: white; font-size: 0.8em; text-transform: uppercase; }}
            .badge.math {{ background: #3498db; }}
            .badge.phy {{ background: #e74c3c; }}
            .badge.chem {{ background: #f1c40f; color: #333; }}
            .q-text {{ font-size: 1.1em; margin-bottom: 15px; line-height: 1.6; color: #2c3e50; }}
            .img-box {{ border: 1px solid #e1e4e8; padding: 10px; margin: 10px 0; background: #fafafa; text-align: center; border-radius: 4px; }}
            .img-box img {{ max-width: 100%; max-height: 400px; }}
            .options {{ list-style: none; padding: 0; }}
            .options li {{ margin-bottom: 8px; padding: 8px; background: #f8f9fa; border-radius: 4px; border: 1px solid #eee; display: flex; align-items: flex-start; gap: 10px; }}
            .options li img {{ max-height: 80px; border: 1px solid #ddd; }}
            .meta {{ font-size: 0.9em; color: #7f8c8d; margin-top: 10px; border-top: 1px dashed #eee; padding-top: 10px; }}
        </style>
        <script>
        window.MathJax = {{
          tex: {{
            inlineMath: [['$', '$'], ['\\\\(', '\\\\)']]
          }},
          svg: {{
            fontCache: 'global'
          }}
        }};
        </script>
        <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
    </head>
    <body>
        <div class="container">
            <h1>Verification Report: {outer_set_name}</h1>
            <p>Total Questions: {len(all_questions)} | Generated by Gemini V2</p>
            <hr>
    """
    
    for q in all_questions:
        sub = q.get("subject", "Unknown").lower()
        color_class = "phy" if "phy" in sub else "chem" if "chem" in sub else "math" if "math" in sub else "math"
        
        # Function to process text for proper LaTeX rendering
        def process_latex(text):
            if not text:
                return ""
            # Replace backslash-space with proper LaTeX
            text = str(text)
            # Wrap common LaTeX patterns in $...$ for MathJax
            import re
            # Already has $...$ - leave as is
            if '$' in text:
                return text
            # Check if text contains LaTeX-like patterns
            latex_patterns = [r'\\mu', r'\\alpha', r'\\beta', r'\\gamma', r'\\theta', r'\\pi', 
                            r'\\frac', r'\\sqrt', r'\\sum', r'\\int', r'\\times', r'\\div',
                            r'\\rightarrow', r'\\leftarrow', r'\\omega', r'\\Delta', r'\\lambda',
                            r'\^', r'_\{', r'\\text', r'\\mathrm', r'\\cos', r'\\sin', r'\\tan']
            has_latex = any(re.search(p, text) for p in latex_patterns)
            if has_latex:
                # Wrap the entire text or detected patterns
                # Simple approach: wrap whole text in display mode if it looks like math
                return f"${text}$"
            return text
        
        # Determine Inner Set for Image Paths (e.g. PHY_SET_1)
        inner_set = q.get("set", "")
        
        # Image Path: ./PHY_SET_1/image.png
        def get_img_html(img_name):
            if not img_name: return ""
            rel_path = f"./{inner_set}/{img_name}"
            return f'<div class="img-box"><img src="{rel_path}" alt="Q Image"></div>'
            
        q_img_html = get_img_html(q.get("image_question"))
        
        # Options Logic: Match Text and Image
        opts_html = '<ul class="options">'
        options_text = q.get("options", [])
        image_options = q.get("image_option", [])
        
        # We assume max of 4 options usually, but iterate safely
        max_idx = max(len(options_text), len(image_options)) if (options_text or image_options) else 0
        
        for i in range(max_idx):
            txt = options_text[i] if i < len(options_text) else ""
            
            # Find matching image for this index if possible
            # Logic: Check if any image file contains "_OPTION{i+1}"
            img_tag = ""
            for img_file in image_options:
                if f"_OPTION{i+1}" in img_file:
                    rel = f"./{inner_set}/{img_file}"
                    img_tag = f'<img src="{rel}">'
                    break
            
            # If no specific tagged image, but we have images and text is missing/placeholder?
            # For now stick to strict mapping match or just list
            
            opts_html += f"<li><span>{process_latex(txt)}</span>{img_tag}</li>"
            
        opts_html += "</ul>"
        
        html += f"""
        <div class="card {color_class}">
            <div class="header">
                <span>Q{q.get('question_no')} <span class="badge {color_class}">{sub}</span></span>
                <span>{q.get('question_type')}</span>
            </div>
            <div class="q-text">{process_latex(q.get('question_txt'))}</div>
            {q_img_html}
            {opts_html}
            <div class="meta">
                <strong>Answer:</strong> {q.get('answer', 'N/A')} | <strong>Set:</strong> {inner_set}
            </div>
        </div>
        """
        
    html += "</div></body></html>"
    
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)
    print(f"  [HTML] Generated: {output_path}")

def verify_sets():
    if not os.path.exists(ROOT_DIR):
        print(f"[ERR] Output directory not found: {ROOT_DIR}")
        return

    # Find Outer Folders matches "JEE_*_SET_*"
    # os.listdir returns names, we check if valid folder
    outer_folders = []
    try:
        nodes = os.listdir(ROOT_DIR)
        for n in nodes:
            full_p = os.path.join(ROOT_DIR, n)
            if os.path.isdir(full_p) and "JEE" in n and "SET" in n:
                outer_folders.append(n)
    except Exception as e:
        print(f"[ERR] Failed to list {ROOT_DIR}: {e}")
        return

    print(f"Found {len(outer_folders)} Outer Sets to Verify.")
    
    for outer in outer_folders:
        outer_path = os.path.join(ROOT_DIR, outer)
        
        combined_questions = []
        
        inner_folders = [d for d in os.listdir(outer_path) if os.path.isdir(os.path.join(outer_path, d))]
        
        print(f"\nVerifying: {outer}")
        
        for inner in inner_folders:
            inner_path = os.path.join(outer_path, inner)
            json_files = glob.glob(os.path.join(inner_path, "*.json"))
            
            for jf in json_files:
                try:
                    with open(jf, "r", encoding="utf-8") as f:
                        data = json.load(f)
                        if isinstance(data, list):
                            combined_questions.extend(data)
                except Exception as e:
                    print(f"  [ERR] Bad JSON {jf}: {e}")
                    
        # Verification Statistics
        total = len(combined_questions)
        q_ids = sorted([int(q.get("question_no", 0)) for q in combined_questions])
        
        missing = []
        if total > 0:
            expected_max = 90 if q_ids[-1] > 75 else 75
            full_range = set(range(1, expected_max + 1))
            found_set = set(q_ids)
            missing = sorted(list(full_range - found_set))
            
        print(f"  > Total Qs: {total} (Range 1-{q_ids[-1] if q_ids else 0})")
        
        sub_counts = {"physics": 0, "chemistry": 0, "math": 0}
        for q in combined_questions:
            s = q.get("subject", "").lower()
            if "phy" in s: sub_counts["physics"] += 1
            elif "chem" in s: sub_counts["chemistry"] += 1
            elif "math" in s: sub_counts["math"] += 1

        print(f"  > Counts: Phy={sub_counts['physics']}, Chem={sub_counts['chemistry']}, Math={sub_counts['math']}")

        if missing:
            print(f"  [FAIL] Missing Qs: {missing}")
        else:
            print(f"  [PASS] Continuity check OK.")
            
        # Generate Report
        report_path = os.path.join(outer_path, "VERIFICATION_REPORT.html")
        generate_html_report(outer, combined_questions, report_path)

if __name__ == "__main__":
    verify_sets()
